spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clickroom
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Themanchuriangold123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql